version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - mvn package
artifacts:
  files:
    - target/api-0.0.1-SNAPSHOT-aws.jar
  discard-paths: yes


