service: simple-aws-lambda

provider:
  name: aws
  runtime: java11
  timeout: 30
  memorySize: 1024

package:
  artifact: target/api-0.0.1-SNAPSHOT-aws.jar

functions:
  simpleLambda:
    handler: com.api.AWSHandler::handleRequest
