package com.api.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Builder
@DynamoDBTable(tableName = "autor")
public class Autor {

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute(attributeName = "nombre")
	private String nombre;

	@DynamoDBAttribute(attributeName = "apellido")
	private String apellido;

	@DynamoDBAttribute(attributeName = "biografia")
	private String biografia;

	@DynamoDBAttribute(attributeName = "libros")
	private List<Libro> libros = new ArrayList<Libro>();
}
