package com.api.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Builder
@DynamoDBTable(tableName = "localidad")
public class Localidad {

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute(attributeName = "denominacion")
	private String denominacion;

	@DynamoDBAttribute(attributeName = "domicilios")
	private List<Domicilio> domicilios = new ArrayList<Domicilio>();

}
